### PR TITLE
Standardize formatting, using google-java-format

### PR DESCRIPTION
**Pull request by mdernsta**
*Description of changes:*
Standardize formatting, using google-java-format

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mernst** [comment]
@martinschaef Could you review and merge this?

**Comment by mdernsta** [comment]
@martinschaef Could you review and merge this?

**Comment by martinschaef** [comment]
@mdernsta is this merge correct?

**Comment by mernstcheckerframework** [comment]
I don't see anything wrong with the merge.

**Comment by mdernsta** [comment]
I don't see anything wrong with the merge.  (Was there a conflict?)

**Pull request merged**
